/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SantaGeneratorRouteImport } from './routes/santa-generator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiFloorPriceRouteImport } from './routes/api.floor-price'
import { Route as ApiLiquidiumRouteImport } from './routes/api.liquidium'
import { Route as ApiSantaGeneratorRouteImport } from './routes/api.santa-generator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SantaGeneratorRoute = SantaGeneratorRouteImport.update({
  id: '/santa-generator',
  path: '/santa-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFloorPriceRoute = ApiFloorPriceRouteImport.update({
  id: '/api/floor-price',
  path: '/api/floor-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiquidiumRoute = ApiLiquidiumRouteImport.update({
  id: '/api/liquidium',
  path: '/api/liquidium',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSantaGeneratorRoute = ApiSantaGeneratorRouteImport.update({
  id: '/api/santa-generator',
  path: '/api/santa-generator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/santa-generator': typeof SantaGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/floor-price': typeof ApiFloorPriceRoute
  '/api/liquidium': typeof ApiLiquidiumRoute
  '/api/santa-generator': typeof ApiSantaGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/santa-generator': typeof SantaGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/floor-price': typeof ApiFloorPriceRoute
  '/api/liquidium': typeof ApiLiquidiumRoute
  '/api/santa-generator': typeof ApiSantaGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/santa-generator': typeof SantaGeneratorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/floor-price': typeof ApiFloorPriceRoute
  '/api/liquidium': typeof ApiLiquidiumRoute
  '/api/santa-generator': typeof ApiSantaGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/robots.txt'
    | '/santa-generator'
    | '/sitemap.xml'
    | '/api/floor-price'
    | '/api/liquidium'
    | '/api/santa-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/robots.txt'
    | '/santa-generator'
    | '/sitemap.xml'
    | '/api/floor-price'
    | '/api/liquidium'
    | '/api/santa-generator'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/robots.txt'
    | '/santa-generator'
    | '/sitemap.xml'
    | '/api/floor-price'
    | '/api/liquidium'
    | '/api/santa-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SantaGeneratorRoute: typeof SantaGeneratorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiFloorPriceRoute: typeof ApiFloorPriceRoute
  ApiLiquidiumRoute: typeof ApiLiquidiumRoute
  ApiSantaGeneratorRoute: typeof ApiSantaGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santa-generator': {
      id: '/santa-generator'
      path: '/santa-generator'
      fullPath: '/santa-generator'
      preLoaderRoute: typeof SantaGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/floor-price': {
      id: '/api/floor-price'
      path: '/api/floor-price'
      fullPath: '/api/floor-price'
      preLoaderRoute: typeof ApiFloorPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liquidium': {
      id: '/api/liquidium'
      path: '/api/liquidium'
      fullPath: '/api/liquidium'
      preLoaderRoute: typeof ApiLiquidiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/santa-generator': {
      id: '/api/santa-generator'
      path: '/api/santa-generator'
      fullPath: '/api/santa-generator'
      preLoaderRoute: typeof ApiSantaGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SantaGeneratorRoute: SantaGeneratorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiFloorPriceRoute: ApiFloorPriceRoute,
  ApiLiquidiumRoute: ApiLiquidiumRoute,
  ApiSantaGeneratorRoute: ApiSantaGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
